# Generated by Django 5.1.7 on 2025-03-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("generated_lyrics", models.TextField()),
                ("music_file", models.FileField(upload_to="music/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
